repos:
  - repo: local
    hooks:
      - id: lint-ruff-check
        name: ğŸ¾ Lint Ruff Check
        entry: make lint-ruff-check
        language: system
        types: [python]
      - id: sec-detect-secrets-hook
        name: ğŸ”’ Lint Detect Secrets Hook
        entry: make sec-detect-secrets-hook
        language: system
        always_run: true
      - id: format-ruff-check
        name: ğŸ¨ Format Ruff Check
        entry: make format-ruff-check
        language: system
        types: [python]
      - id: typecheck-pyright
        name: ğŸ” Typecheck Pyright
        entry: make typecheck-pyright
        language: system
        types: [python]
